apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {클러스터의 certificate-authority-data 값}
    server: {클러스터 server 값}
  name: k8s-clu
contexts:
- context:
    cluster: k8s-clu
    user: k8s-clu-admin
  name: k8s-clu-admin@k8s-clu
current-context: k8s-clu-admin@k8s-clu
kind: Config
preferences: {}
users:
- name: k8s-clu-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoi.io/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "{사용자 액세스 키 ID 입력}"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "{사용자 API 액세스 보안 키 입력}"
      - name: "OS_REGION_NAME"
        value: "kr-central-2"
  provideClusterInfo: false
