apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {클러스터의 certificate-authority-data}
    server: {클러스터의 server 값}
  name: {클러스터 이름}
contexts:
- context:
    cluster: {클러스터 이름}
    user: {클러스터 이름}-admin
  name: {클러스터 이름}-admin@{클러스터 이름}
current-context: {클러스터 이름}-admin@{클러스터 이름}
kind: Config
preferences: {}
users:
- name: {클러스터 이름}-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaocloud.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "{액세스 키 ID 입력}"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "{사용자 API 보안 액세스 키 입력}"
      - name: "OS_REGION_NAME"
        value: "kr-central-2"
